// Surge port inspired by MaYIHEI/paperclip loon/ipquality
// Checks the CURRENT Surge routing egress (not an arbitrary selected Loon node).
const H={"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1","Accept-Language":"en-US,en;q=0.9"};
const BACKEND="https://ipinfo.check.place";
function req(url,opts={}){return new Promise((resolve,reject)=>{const o={url,headers:opts.headers||H};if(opts.body!==undefined)o.body=opts.body;const cb=(e,r,b)=>{if(e)return reject(e);resolve({status:Number(r.status||r.statusCode),body:String(b||"")})};(opts.method==="POST"?$httpClient.post:$httpClient.get)(o,cb)})}
function json(url,opts={}){return req(url,opts).then(x=>JSON.parse(x.body))}
function trace(s){const o={};String(s).split(/\r?\n/).forEach(l=>{const i=l.indexOf("=");if(i>0)o[l.slice(0,i)]=l.slice(i+1)});return o}
function cap(p){return Promise.resolve(p).then(v=>({ok:1,v}),e=>({ok:0,e:String(e)}))}
async function ipInfo(){let a=await cap(req(BACKEND+"/cdn-cgi/trace"));if(a.ok){let t=trace(a.v.body);if(t.ip)return {ip:t.ip,loc:t.loc||""}}let b=await json("https://api4.ipify.org?format=json");return {ip:b.ip,loc:""}}
async function db(ip){let a=await cap(json(BACKEND+"/"+encodeURIComponent(ip)+"?lang=cn"));return a.ok?a.v:{}}
async function yt(){try{let r=await req("https://www.youtube.com/premium");if(/Premium is not available in your country/i.test(r.body))return "❌ YouTube  不可用";let m=r.body.match(/\"(?:countryCode|contentRegion)\"\s*:\s*\"([A-Z]{2})\"/i);return "✅ YouTube  解锁"+(m?" · ["+m[1].toUpperCase()+"]":"")}catch(e){return "⚪ YouTube  未确认"}}
async function nf(){try{let r=await req("https://www.netflix.com/title/81280792");if(r.status===403)return "❌ Netflix  不可用";if(r.status===404)return "🟠 Netflix  仅自制剧/部分可用";return r.status>=200&&r.status<400?"✅ Netflix  解锁":"⚪ Netflix  未确认"}catch(e){return "⚪ Netflix  未确认"}}
async function gpt(){try{let [w,a,t]=await Promise.all([cap(req("https://api.openai.com/compliance/cookie_requirements",{headers:Object.assign({},H,{Authorization:"Bearer null",Origin:"https://platform.openai.com"})})),cap(req("https://ios.chat.openai.com/")),cap(req("https://chatgpt.com/cdn-cgi/trace"))]);let loc=t.ok?(trace(t.v.body).loc||""):"";let wb=w.ok&&!/unsupported_country|access denied|blocked/i.test(w.v.body);let ap=a.ok&&!/unsupported_country|disallowed isp|access denied|blocked/i.test(a.v.body);let s=wb&&ap?"✅ ChatGPT  解锁":(wb||ap?"🟠 ChatGPT  部分可用":"❌ ChatGPT  不可用");return s+(loc?" · ["+loc+"]":"")}catch(e){return "⚪ ChatGPT  未确认"}}
async function disney(){try{let r=await req("https://www.disneyplus.com/");if(r.status===200&&!/not available in your region/i.test(r.body))return "✅ Disney+  可访问";return "❌ Disney+  不可用"}catch(e){return "⚪ Disney+  未确认"}}
async function run(){let i=await ipInfo(),d=await db(i.ip);let info=d.Info||d.info||{},type=d.Type||d.type||{},risk=d.Risk||d.risk||{};let org=info.Organization||info.organization||"";let asn=info.ASN||info.asn||"";let region=(info.Region&&(info.Region.Name||info.Region.Code))||i.loc||"";let city=(info.City&&(info.City.Name||info.City.name))||"";let usage=(type.Usage&&(type.Usage.IPinfo||type.Usage.ipinfo))||"";let lines=["IP: "+i.ip,["地区",region,city].filter(Boolean).join(" · "),["ASN",asn,org].filter(Boolean).join(" · "),usage?"类型: "+usage:""];let media=await Promise.all([yt(),nf(),disney(),gpt()]);lines=lines.filter(Boolean).concat(["","流媒体与 AI"],media);$done({title:"节点 IP 质量检测",content:lines.join("\n"),icon:"shield.lefthalf.filled","icon-color":"#30D158"})}
run().catch(e=>$done({title:"节点 IP 质量检测",content:"检测失败："+String(e),icon:"network.slash"}));